export type CatalogReview = {
  id: string;
  title: string;
  year: string;
  genre: string;
  runtime: number;
  contentRating?: string;
  color: string;
  rating: number;
  blurb: string;
  reviewText: string;
  favoriteQuote?: string;
  rewatchOdds?: string;
  watchParty?: string;
  sleepRisk?: string;
  poster: string;
  letterboxdUrl: string;
};

export const fallbackReviews: CatalogReview[] = [
  {
    id: "letterboxd-i-swear",
    title: "I Swear",
    year: "2025",
    genre: "History / drama",
    runtime: 121,
    contentRating: "NR",
    color: "#355245",
    rating: 9.2,
    blurb: "So many emotions, all fueled by a spectacular performance by Robert Aramayo.",
    reviewText: "“Sometimes what I say is funny and I even laugh myself, but that’s very different to actively teasing, or mocking, or encouraging people to swear.”\n\nSo many emotions, all fueled by a spectacular performance by Robert Aramayo. It strikes this balance of a biopic, being informative, but being a damn good movie at the core. It’s super cool that, as an extension of Davidson’s attempt to spread awareness of Tourette’s, this movie was born and executed beautifully.",
    poster: "https://a.ltrbxd.com/resized/alternative-poster/1/1/9/7/8/4/2/p/jm6sHwVMWy1Izk8Mgmjcza6kxMJ-0-600-0-900-crop.jpg?v=3edb3dc630",
    letterboxdUrl: "https://letterboxd.com/foodiefrank/film/i-swear/",
  },
  {
    id: "letterboxd-demolition",
    title: "Demolition",
    year: "2015",
    genre: "Drama / comedy",
    runtime: 101,
    contentRating: "R",
    color: "#596451",
    rating: 7.8,
    blurb: "It’s an interesting take on loss and how it can affect you.",
    reviewText: "Although there are some parts that seemingly, in my opinion, don’t mesh well together or belong in the same movie, I enjoyed this. It’s an interesting take on loss and how it can affect you. Not as many raw emotion moments as I would have liked but that is also kind of the point.",
    poster: "https://a.ltrbxd.com/resized/alternative-poster/2/3/0/8/3/2/p/oz5zHHaaQJru31FS5HgLKK6QWA8-0-600-0-900-crop.jpg?v=44e6bab769",
    letterboxdUrl: "https://letterboxd.com/foodiefrank/film/demolition/",
  },
  {
    id: "letterboxd-end-of-watch",
    title: "End of Watch",
    year: "2012",
    genre: "Drama / thriller / crime",
    runtime: 109,
    contentRating: "R",
    color: "#4b514a",
    rating: 5.9,
    blurb: "Incredibly tough watch - will not watch again.",
    reviewText: "I wish they either leaned into the self-filmed part all the way or left it out. Why was everyone else filming? It was a slow burn for a while but vital for setting everything up.\n\nIncredibly tough watch - will not watch again.",
    poster: "https://a.ltrbxd.com/resized/film-poster/6/3/4/6/2/63462-end-of-watch-0-600-0-900-crop.jpg?v=da5e26db65",
    letterboxdUrl: "https://letterboxd.com/foodiefrank/film/end-of-watch/",
  },
  {
    id: "letterboxd-invictus",
    title: "Invictus",
    year: "2009",
    genre: "History / drama",
    runtime: 134,
    contentRating: "PG-13",
    color: "#755f3f",
    rating: 7.1,
    blurb: "Parts were amazing, parts were meh.",
    reviewText: "Parts were amazing, parts were meh. There are some deeper messages throughout the movie that are powerful and worth a thought. I had a good time learning more about rugby and Nelson Mandela.\n\n#8 of watching every Matt Damon movie in prep for The Odyssey",
    poster: "https://a.ltrbxd.com/resized/film-poster/3/7/6/0/5/37605-invictus-0-600-0-900-crop.jpg?v=4cf7d9e769",
    letterboxdUrl: "https://letterboxd.com/foodiefrank/film/invictus/",
  },
  {
    id: "letterboxd-the-batman",
    title: "The Batman",
    year: "2022",
    genre: "Crime / mystery / thriller",
    runtime: 177,
    contentRating: "PG-13",
    color: "#3b3030",
    rating: 9.8,
    blurb: "Still badass.",
    reviewText: "Still badass.",
    poster: "https://a.ltrbxd.com/resized/alternative-poster/3/4/8/9/1/4/p/tdWJFXQZzzI8TIJQ54vLaQ50bW2-0-600-0-900-crop.jpg?v=e5d27db670",
    letterboxdUrl: "https://letterboxd.com/foodiefrank/film/the-batman/",
  },
  {
    id: "letterboxd-the-informant",
    title: "The Informant!",
    year: "2009",
    genre: "Comedy / Crime / Drama",
    runtime: 108,
    contentRating: "R",
    color: "#7b713c",
    rating: 6.1,
    blurb: "The plot was interesting and Matt Damon did good, but the comedy gets overplayed.",
    reviewText: "To be fair, I haven’t watched many other Steven Soderbergh films (yet) but I wasn’t a huge fan of the stylistic choices made throughout. The plot was interesting and I do think Matt Damon did good in his role. It has some good comedy pieces but it does overplay the comedy aspect a little IMO.\n\nThe last 10-15 minutes were the best part by far.\n\n#7 of watching every Matt Damon movie in prep for The Odyssey",
    poster: "https://a.ltrbxd.com/resized/alternative-poster/4/5/4/1/0/p/iBCzdj22caOLJaNpOvEmFGt0h02-0-600-0-900-crop.jpg?v=638fcc071a",
    letterboxdUrl: "https://letterboxd.com/foodiefrank/film/the-informant-2009/",
  },
  {
    id: "letterboxd-air",
    title: "Air",
    year: "2023",
    genre: "Drama / history",
    runtime: 112,
    contentRating: "R",
    color: "#a8623b",
    rating: 8.2,
    blurb: "It doesn’t focus on MJ, but Nike and the people behind the creation of the Air Jordan brand.",
    reviewText: "“I believe the saying that if you say what you want, that’s fine and good, but doing something about it, now… that’s what really counts”\n\nI think Air works really well because it doesn’t focus on MJ, but Nike and the people behind the creation of the Air Jordan brand. I really like Ben Affleck’s directing style in this and with all of the big names in this, it was set up for success.\n\n#6 of watching every Matt Damon movie in prep for The Odyssey",
    poster: "https://a.ltrbxd.com/resized/alternative-poster/8/6/8/4/9/1/p/iKcnbqhKvlwfF4CnMVlRrYlOvM5-0-600-0-900-crop.jpg?v=781672961f",
    letterboxdUrl: "https://letterboxd.com/foodiefrank/film/air-2023/",
  },
  {
    id: "letterboxd-the-brothers-grimm",
    title: "The Brothers Grimm",
    year: "2005",
    genre: "Adventure / Comedy / Fantasy",
    runtime: 118,
    contentRating: "PG-13",
    color: "#584c3d",
    rating: 3.8,
    blurb: "What in the Scooby Doo shit is this?",
    reviewText: "What in the Scooby Doo shit is this? You may think that with a movie where the main actors are Matt Damon and Heath Ledger it’s destined to be good. Wrong. They’re only as good as the writing can make them. It just never grabbed me and I did not love the comedy style the movie was going for.\n\n#5 of watching every Matt Damon movie in prep for The Odyssey",
    poster: "https://a.ltrbxd.com/resized/film-poster/4/9/3/3/3/49333-the-brothers-grimm-0-600-0-900-crop.jpg?v=92a8365d8f",
    letterboxdUrl: "https://letterboxd.com/foodiefrank/film/the-brothers-grimm/",
  },
  {
    id: "letterboxd-jurassic-park",
    title: "Jurassic Park",
    year: "1993",
    genre: "Adventure / Science Fiction / Thriller",
    runtime: 127,
    contentRating: "PG-13",
    color: "#574932",
    rating: 9.1,
    blurb: "A classic that still looks so good and completely sucks you into its world.",
    reviewText: "Watching this is 2026 is crazy because it still looks so good. The plot just sucks you in and I didn’t realize how detail-oriented and immersive the world building is. A classic that went on to create a very mediocre franchise.",
    poster: "https://a.ltrbxd.com/resized/alternative-poster/5/1/7/3/3/p/uvQmTMXLWTFxRkbvnLyeBJV1K0w-0-600-0-900-crop.jpg?v=c9fd8f7048",
    letterboxdUrl: "https://letterboxd.com/foodiefrank/film/jurassic-park/",
  },
  {
    id: "letterboxd-chef",
    title: "Chef",
    year: "2014",
    genre: "Comedy / Drama",
    runtime: 114,
    contentRating: "R",
    color: "#a45235",
    rating: 9.9,
    blurb: "A masterclass by Jon Favreau. Everything about Chef works for me.",
    reviewText: "A masterclass by Jon Favreau. Everything about Chef works for me. Call me biased as I worked in kitchens all throughout high school and college but Chef is a great story focused around something that unites us all - food.\n\nChef teaches you about food while also delivering this wholesome family-oriented story. The cast speaks for itself with R.D.J., Scarlett Johansson, John Leguizamo, Dustin Hoffman, Sofía Vergara, and many others. It is just perfect.",
    poster: "https://a.ltrbxd.com/resized/alternative-poster/1/5/1/3/0/9/p/iTvTLl7RuFGDlsKmj4tQdCcpOVm-0-600-0-900-crop.jpg?v=163487851b",
    letterboxdUrl: "https://letterboxd.com/foodiefrank/film/chef/",
  },
  {
    id: "letterboxd-the-king",
    title: "The King",
    year: "2019",
    genre: "Drama / History / War",
    runtime: 140,
    contentRating: "R",
    color: "#403a31",
    rating: 8.9,
    blurb: "The pacing is slow, but the stunning cinematography more than makes up for it.",
    reviewText: "To preface this review, I’m a massive Joel Edgerton fan.\n\nYes, the pacing can be a little slow. I think this is made up for by the absolutely stunning cinematography though. I don’t think Timothée is great at faking an accent, but he is great at acting. I really enjoyed this throughout and, personally, I think the 2.5 hour runtime was about right to set everything up and really immerse you in this 15th century timepiece.",
    poster: "https://a.ltrbxd.com/resized/alternative-poster/4/3/4/7/5/3/p/igS2oqoK9yqYsyyeSuwJ8tIWEX0-0-600-0-900-crop.jpg?v=45b2b4b792",
    letterboxdUrl: "https://letterboxd.com/foodiefrank/film/the-king-2019/",
  },
  {
    id: "letterboxd-stuck-on-you",
    title: "Stuck on You",
    year: "2003",
    genre: "Comedy",
    runtime: 118,
    contentRating: "PG-13",
    color: "#426354",
    rating: 5.8,
    blurb: "It wanted so desperately to be like Step Brothers and barely missed the mark.",
    reviewText: "For a movie that wanted so desperately to be like Step Brothers it just barely missed the mark. The characters aren’t inherently funny but the writing had a chance to make up for that - too bad it fell short.\n\nThe funniest parts of the movie were after they got separated with the clips of them having muscle memory of being together.\n\n#4 of watching every Matt Damon movie in prep for The Odyssey",
    poster: "https://a.ltrbxd.com/resized/alternative-poster/5/0/7/9/0/p/aTy6zNMGNJQYZho3Lcw2OoQQAT5-0-600-0-900-crop.jpg?v=bff51f42b8",
    letterboxdUrl: "https://letterboxd.com/foodiefrank/film/stuck-on-you/",
  },
];
